spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?allowPublicKeyRetrieval=true
    username: demo
    password: welcome
    hikari:
      auto-commit: false
      connection-timeout: 3000
      max-lifetime: 180000
      maximum-pool-size: 10
      data-source-properties:
        cachePrepStmts: true
        rewriteBatchedStatements: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        format_sql: true
        hbm2ddl.auto: none
  flyway:
    enabled: true
    validate-migration-naming: true
    # locations: classpath:db/migration/common
    # url: jdbc:mysql://127.0.0.1:3306/demo?allowPublicKeyRetrieval=true
    # user: flyway
    # password: welcome
    clean-on-validation-error: true
